# Generated by Django 5.2.15 on 2026-06-20 18:59

import django.db.models.deletion
import launch.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0001_initial"),
        ("platform_config", "0002_ltitoolregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LTILaunchState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default=launch.models.generate_token,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        default=launch.models.generate_token, max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platform_config.ltitoolregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
