# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0002_ltilaunchstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ltilaunchstate",
            name="context_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ltilaunchstate",
            name="context_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ltilaunchstate",
            name="context_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ltilaunchstate",
            name="target_link_uri",
            field=models.URLField(blank=True, default=""),
        ),
    ]
