# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0003_ltilaunchstate_context_fields"),
        ("platform_config", "0003_remove_ltitoolregistration_context_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_link_uri", models.URLField(blank=True, null=True, unique=True)),
                ("context_id", models.CharField(blank=True, default="", max_length=255)),
                ("context_label", models.CharField(blank=True, default="", max_length=255)),
                ("context_title", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platform_config.ltitoolregistration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ltilaunchstate",
            name="launch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="launch.launch",
            ),
        ),
    ]
