# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0004_launch_and_state_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="target_link_uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
