location /static {
	alias /srv/lti13-simulator/deploystatic;
	expires 1h;
	add_header Cache-Control "public, max-age=3600";
}



location / {
	uwsgi_pass  unix:/srv/lti13-simulator/backend/lti13-simulator.sock;
	include     /srv/lti13-simulator/uwsgi_params; 
}
