# Generated by Django 5.2.15 on 2026-06-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LTIToolRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("oidc_init_url", models.URLField()),
                ("launch_url", models.URLField()),
                ("tool_jwks_url", models.URLField()),
                ("target_link_uri", models.URLField()),
                ("deployment_id", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("context_id", models.CharField(max_length=255)),
                ("context_label", models.CharField(max_length=255)),
                ("context_title", models.CharField(max_length=255)),
                ("resource_link_id", models.CharField(max_length=255)),
            ],
        ),
    ]
