# Generated by Codex on 2026-06-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_config", "0002_ltitoolregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ltitoolregistration",
            name="context_id",
        ),
        migrations.RemoveField(
            model_name="ltitoolregistration",
            name="context_label",
        ),
        migrations.RemoveField(
            model_name="ltitoolregistration",
            name="context_title",
        ),
    ]
